---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
setwd("/home/suhishan/Documents/Final Sem Research/Conflict/")
library(haven)
library(tidyverse)
library(stargazer)
library(geodata)
library(sf)
library(patchwork)
library(dagitty)

#These packages are for html scraping.
library(rvest)
library(xml2)

theme_set(theme_minimal() +
            theme(panel.grid = element_blank()))

```

Some preliminary look at means to see the parallel trends.

```{r}
# load datasets.
nlfs <- read_dta("appended_nlfs.dta")
conflict <- read_dta("final_conflict.dta")

#1991 means for treatment and control
info_91 <-  conflict %>% group_by(treatment) %>% 
  summarize(
    info_91 =  mean(total_emp/popn_over_10) *100
  )

# 1998  means

info_98 <- nlfs %>% 
  filter(nlfs_year == 1998 & age>10) %>% 
  group_by(treatment) %>% 
  summarize(
    info_98  =  mean(usually_emp, na.rm =T)  * 100
  )
  
#2008 means
info_08 <- nlfs %>% 
  filter(nlfs_year == 2008 > age>10) %>% 
  group_by(treatment) %>% 
  summarize(
    info_08  =  mean(usually_emp, na.rm =T) * 100  
  )

bind_cols(info_91, info_98[,2], info_08[,2]) %>% 
  pivot_longer(
    cols = c(info_91, info_98, info_08),
    names_to = "data_year",
    values_to = "emp"
  ) %>% 
  mutate(treatment = c(0,0,0,1,1,1),
         year = c(1, 8, 18, 1, 8, 18)) %>% 
  ggplot(aes(x = year , y = emp)) +
  geom_line(aes(group = treatment, col = treatment))
  


```

Extremely Preliminary First Stagre Regression:


```{r}
c <- read_dta("final_conflict.dta")

c <- c  %>% 
  mutate(forest_cover = round(norm_forest * 100, 3),
         poverty_rate = round(pov_rate * 100, 3),
         high_forest = ifelse(forest_cover > quantile(forest_cover, 0.75, na.rm =T),1, 0),
         deaths_per_1000 = (best_est/TotalPopn) * 1000 )


#First Stage Plot of Conflict Deaths and forest cover.


m1 <- lm(best_est ~ forest_cover, c)
m2 <- lm(best_est ~ high_forest + elevation_max, c); summary(m2)
m2_1 <- lm(best_est ~ high_forest + elevation_max + propdeaths_pre02 + poverty_rate, c ); summary(m2_1)

m3 <- lm(best_est ~ high_forest + propdeaths_pre02 + elevation_max, c)

stargazer(m1, m2, type = "text")
stargazer(m2, type = "latex", star.cutoffs = NA,
          omit = c("elevation_max"),
          keep.stat = c("n", "rsq","adj.rsq"),
          covariate.labels = c("Forest Cover > p75 (1/0)"),
          dep.var.labels = c("Conflict Deaths"),
          out = "Data Presentation/first_stage_reg.tex",
          notes = NULL,
          notes.append = F)
stargazer(m3, type = "text")

```



















Daggit Model Code for First Stage:

```{r}
first_stage <- dagitty('dag {
"Conflict Deaths" [outcome,pos="-0.056,-0.281"]
"Conflict Incidences" [outcome,pos="-0.309,-0.997"]
"Forest Cover" [exposure,pos="-1.320,-0.262"]
"Poverty Rate" [pos="-1.159,-1.130"]
"Socio economic Inequality" [pos="-0.841,-1.589"]
Elevation [pos="-1.823,-0.926"]
"Conflict Incidences" -> "Conflict Deaths"
"Forest Cover" -> "Conflict Deaths"
"Forest Cover" -> "Conflict Incidences"
"Forest Cover" -> "Poverty Rate"
"Poverty Rate" -> "Conflict Deaths"
"Poverty Rate" -> "Conflict Incidences"
"Socio economic Inequality" -> "Conflict Incidences"
"Socio economic Inequality" -> "Poverty Rate"
Elevation -> "Forest Cover"
Elevation -> "Poverty Rate"
}')

```



